[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
if self.ability.name == 'Loyalty Card' then
'''
position = "at"
payload = '''
if false and self.ability.name == 'Loyalty Card' then -- killed by vanillarebalanced
'''
match_indent = true

